name: BUPT ncov clock in
on:
  schedule:
    - cron: "50 8,11,17 * * *"


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
        
          
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Run CLOCK_IN
        run: |
          python3 main.py
        env:
          USERS: ${{ secrets.USERS }}
          DATA: ${{ secrets.DATA }}
